"""adicionando coluna de vezes renovado na tabela de emprestimos

Revision ID: 14c4a906af5a
Revises: 79453b9aba69
Create Date: 2026-04-17 20:44:03.017895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c4a906af5a'
down_revision: Union[str, Sequence[str], None] = '79453b9aba69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emprestimo', sa.Column('vezes_renovado', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emprestimo', 'vezes_renovado')
    # ### end Alembic commands ###
