"""adicionando colunas livro

Revision ID: 7ca8a4060c42
Revises: 98cfa76b1ee7
Create Date: 2026-04-12 21:37:50.522262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca8a4060c42'
down_revision: Union[str, Sequence[str], None] = '98cfa76b1ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livros', sa.Column('isbn', sa.String(), nullable=True))
    op.add_column('livros', sa.Column('quantidade_disponivel', sa.Integer(), nullable=True))
    op.add_column('livros', sa.Column('categoria', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livros', 'categoria')
    op.drop_column('livros', 'quantidade_disponivel')
    op.drop_column('livros', 'isbn')
    # ### end Alembic commands ###
